Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

    Given that A is an ndarray object, many functionalities in numpy could be accessed by:
        Make sure to explain each line of codes that you have created.

    Using a property of the ndarray object
        e.g. A.shape
    Using a method of the ndarray object
        e.g. A.max()
    Using a numpy function and passing an ndarray
        e.g. np.max(A)

B. Create a 5x5 integer-array filled with ones.

    Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [3]:
#A.
import numpy as np


In [4]:
A = np.array([7,17,2,29,4,59,14,100]) #i created an array, array A with numbers inside it
A

array([  7,  17,   2,  29,   4,  59,  14, 100])

In [5]:
A.max() #finds the maximum (largest) number in the array "A".

100

In [7]:
A.shape #tells how many elements are in each dimension of the array. Array "A".

(8,)

In [8]:
np.max(A)

100

In [9]:
A.min() #finds the minimum number in the array "A".

2

In [10]:
#B
#B. Create a 5x5 array filled with ones

A = np.ones((5, 5), dtype=int) #I created a new array filed with ones and "A" variable that holds the array filled with ones, (5,5)the no. of rows and columns

print(A)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#B. Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

In [ ]:
A.shape

(5, 5)

In [ ]:
A.size  #tells how many elements are in each dimension of the array. Array "A".

25

In [ ]:
A.ndim  #number of dimensions in array "A"

2

In [ ]:
#C.
C = np.arange(-5, 6) # np.arange(). It generates a sequence of numbers from -5 up to, but not including, 6. So, "C" will contain numbers from -5 to 5.
print(C)
result = C * 2 # then the generated sequence will be multiplied by 2
print(result)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[-10  -8  -6  -4  -2   0   2   4   6   8  10]


Exercise

A. Choose the values from the range of numbers 1 to 100.

    Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
        Explain what is the result briefly by writing a comment before the code.
    Multiply the resulting array with 3. Print the result.


In [ ]:
#A.
#array with 30 values within the specified range, incrementing by 2
A = np.arange(5, 65, 2) # arguments: start, stop, step
print(A)

# Multiply by 3
result = A * 3

print(result)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63]
[ 15  21  27  33  39  45  51  57  63  69  75  81  87  93  99 105 111 117
 123 129 135 141 147 153 159 165 171 177 183 189]


Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.

    Get the dimensions, shape, and size.
        Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.

    Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result? * Write a brief explanation on the multiplication process.

In [15]:
#A.
A = np.random.randint(0, 13, size=(2, 2, 2, 2))#np.random.randint generates random integers and i created a multi-dimensional array named "A" filled with random integers.
print(A)


[[[[ 2  5]
   [ 1  4]]

  [[ 6  5]
   [ 0 10]]]


 [[[ 6  2]
   [ 1  2]]

  [[ 3  1]
   [10  3]]]]


In [16]:
#A.
#Get the dimensions, shape, and size.
A.ndim #number of dimensions

4

In [17]:
A.shape

(2, 2, 2, 2)

In [18]:
A.size

16

In [20]:
#B. Get the maximum number for each dimension and display it

max_dim = A.max(axis=(0, 1, 2, 3)) #

print("Maximum number for each dimension:")
print(max_dim)

Maximum number for each dimension:
10


In [ ]:
#C.
result = A * 4
print(result)

[[[[36 12]
   [16  0]]

  [[ 4 48]
   [36 44]]]


 [[[36  8]
   [40 40]]

  [[16  8]
   [20 20]]]]
